### ISSUE TITLE
XMP freeze (have to shut down) the system 

### ISSUE THREAD

**Issue by carman1tr** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#114]
Hello. First I want to thank you very much for your share and it is very useful not to be crazy :))

I use Gigabyte Z490 Aorus Master and your efi Open Core 0.6.4 Bigger 11.1 (20C69) is working even at Bluetooth correction.
But I have XMP problem on my motherboard. The XMP is not working stable even at windows. I entered settings manually for my 3600 MHZ and (bought new to test) 4266 Mhz rams. When the settings are manually done no problem at Windows but the freeze problem on Mac is still problem. 
When I am afk from Mac, it freeze after 5 minutes, if I try to use Final Cut it freeze, When I try to check HVEC on videoProc it restart.

Any solution for this situation? Thank you very much.

**Comment by savemosca** [comment]
Hi, i have the same problem with z490 Vision D and G.Skill f4-4400c16d-16gtzr. Now i found a workaround setting manually timings and voltage same as F4-3600C16D-16GTZR 16-16-16-36 at 1.35v. I think the problem i related to voltage because if i increase it system freezes or reboots. My RAM model isn't listed in compatibility list for this motherboard but i tried also with a 4400 stick listed but the problem still remain. I've also tried different bios releases but without success.

**Comment by SchmockLord** [comment]
I am happy that you got help from someone, but I will close this as this has nothing to do with the hackintosh config itself.
