### ISSUE TITLE
Thunderbolt 3 Power Delivery

### ISSUE THREAD

**Issue by addisonduda** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#19]
Firstly, thanks so much for this awesome guide. I have an RX 580 in my machine and everything seems to be working great so far. However, I don't seem to have the USB Power Delivery out of the Thunderbolt 3 ports. I am getting some power, but no near the 65 Watts Power Delivery can offer. Is there a way I would be able to fix this? Thanks in advance!

**Comment by SchmockLord** [comment]
Puh. I don't have an idea and I am also not able to test it, sorry. How is the power output on the same port with the same bios settings in Windows?

**Comment by addisonduda** [comment]
Great question. I haven’t gotten around to installing Windows 10 yet. I’ll check back when I do to comment if its working. Thanks anyway! Best!

**Comment by SchmockLord** [comment]
It just came to my mind, that I can plug in my MacBook Pro 16 with the USBC-charging cable. First of all: It loads and hotplug works :). And then I have opened "Battery Health 2" to check the wattage of the charging. It started with 19W and then dropped to 8W. It is unloading faster than it is charging, so the % drops while plugged in.

But: Where is it said, that the USBC/Thunderbolt 3 ports of the Gigabyte Z490 Vision D offer Power Delivery and because you mentioned 65W, where is it said, that they deliver 65W?

I haven't found any information about PowerDelivery so I wouldn't expect it.

Best,
Chris

**Comment by addisonduda** [comment]
It’s listed in the features on their website. I’ve attached a picture. I couldn’t find it anywhere in the manual though. It may just be a mistype on their website...
![90D03446-C750-4EE3-9DE5-3DED814B0A62](https://user-images.githubusercontent.com/66935020/84777680-e8514800-afaf-11ea-9123-2a963391cbab.png)

**Comment by SchmockLord** [comment]
You mean the mention of "Power Delivery 2.0"?

**Comment by addisonduda** [comment]
Yeah, exactly. I think PD 2.0 should give 85 W to devices like our MacBook Pros, but its clearly not. I will try and give Gigabyte a call on this tonight. Hopefully its not marketed wrong on the website. This was a feature I was anticipating, but if it doesn’t work I can definitely live without it.

**Comment by SchmockLord** [comment]
I have just tried it with Windows 10. Started with 18W and then dropped to even less: 2W.

**Comment by SchmockLord** [comment]
Are you using a cable with a thunderbolt 3 logo? Because I think the charger cable that I am using can be used to charge my MBP with a dedicated charger, but not with other Thunderbolt 3 devices. Therefore you need dedicated Thunderbolt 3 cables to use the TB3 Power Delivery Feature.

**Comment by addisonduda** [comment]
No, I wasn't. I was using the USB-C charging cable that came with my MacBook Pro. I have a Thunderbolt 3 coming in the mail tomorrow.

**Comment by addisonduda** [comment]
I just tried the Thunderbolt 3 cable and I do not have Power Delivery. My MacBook Pro says it's not charging when plugged in.

**Comment by SchmockLord** [comment]
Test the same with Windows. Otherwise, we don't if it is the MacOS config or simply because Gigabyte just made marketing promises.

**Comment by kellertobias** [comment]
To my understanding: Power Delivery 2.0 simply is the protocol so that the Device and Host can communicate what voltage the device needs to be charged/ powered. It goes as low as in profile 1 with 5V at 2A which is 10W.

also see: https://www.elektronik-kompendium.de/sites/com/1809251.htm
and https://kompendium.infotip.de/usb_power_delivery.html

**Comment by waelalmeiry** [comment]
Thanks Addison Duda but how can I solve this? I am a Neurosurgeon without any previous experience in Hackintosh this is my first project ever.

**Comment by addisonduda** [comment]
From Gigabyte - "Where are you seeing that it's capable of delivering 65W of power? We do not list the spec on our website."

I guess that solves that...
