### ISSUE TITLE
Better explanation

### ISSUE THREAD

**Issue by khronokernel** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#2]
Hello, so I've seen quite a few people sharing this EFI and I'd like a better understanding of why you did certain things As atm you're not providing much info or even sources on why you've chosen certain things, and worried that a faulty EFI will become popular on Z490 boards since this is the first Z490 EFI on github(as of the time of writing)

So my main concerns:

* ACPI:
  * Why are you including all these ACPI renames? I see they're disabled but looks like you took some laptop EFI and tried it
  * Why do you include USBX twice? Your SSDT-EC already has a USBX device
  * SSDT-EC is missing the genuine EC STA Method allowing AppleACIEC to load(this isn't really an issue, but just looks like you too the same SSDT from Acidanthera and compiled without checking)
* > Audio: Use AppleALC.kext and Layout-id=11. Bootargument "alcid=11"
  * Why do you include layout ID if you know AppleALC doesn't support Z490?
  > Not working so far: Audio (update soon)
* CPU ID Spoof to Coffeelake U
  * Just like to understand the logic behind this, if you're spoofing CPU ID to mobile why not CometLake U which is supported in the kernel? Just seems a bit confusing but would like to understand why mobile Coffeelake over desktop and why your approach works
* Kexts:
  * Why AppleMCEReporterDisabler.kext? MCEReporter doesn't attach on anything but HEDT SMBIOS(MP6/7 and IMP1). Plus this kext is only meant for dual socket systems, does Z490 reports as multi socket?
  * AppleALC: See above
* SMBIOS
  * MacBookAir9,1? very confused
* Install method:
  > Then navigate to Contents > SharedSupport
  > Delete the Installlnfo.plist

Could you elaborate why?  

Thanks in advance

**Comment by SchmockLord** [comment]
Hello,

First of all: As many others I learn with every project. And I do my best to get a better understanding of what all these things do. 

And some of the things you mentioned I know better now and fixed them.

The initial build was working for me and helped many other. 

And without sharing and getting feedback from others like you, my build wouldn't have evolved in the way he already did.

Now your questions:
ACPI: SSDT-AWAC.aml and SSDT-PMC.aml because it was mentioned in the Desktop Guide for Comet Lake. And I didn't notice that SSDT-EC-USBX and SSDT-EC have reduncancies. In my current buil I am only using SSDT-EC-USBX.aml.

Audio: At first I thought layout-id=11 works. But it didn't. No sound. But I found a way to get audio working and updated the audio section.

CPU-ID Spoof: I found this ID in this repository and it worked for me: https://github.com/daliansky/XiaoXinPro-13-hackintosh

Kexts: I removed AppleMCEReporterDisable.kext.

SMBIOS: I thought it might be helpful as MacBookAir9,1 is already using 10th Gen Intel processor. Later I found out that it is not necessary and switched back to iMac19,1.

Install method: I got an error within the catalina installation saying "this installation is damaged". This helped to get over this error. And it was the same for somebody else on the hackintosh-forum.de. But I will add this "in case you get the error ...." in the description.

If you have any more suggestions I am glad to get feedback to make my build better for everyone and learn more :).

Best,
Chris
