### ISSUE TITLE
NVMeFix and config.plist ExecutablePaths

### ISSUE THREAD

**Issue by addisonduda** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#24]
I see that the NVMeFix.kext is in the Kexts folder of your EFI, but is not found in your config.plists. Is there a reason for this? I am using the 970 EVO Plus. 

A few of the other Kexts (RadeonBoost, FakePCIID_Intel_HDMI_Audio, and FakePCIID_Intel_I225-V) do not have ExecutablePaths in the config.plist. Is this how it’s meant to be? If so, why is this different from the others.

Please forgive me if these are very stupid questions. This is my first build and I’m really trying to learn. Your guide has been so valuable. Thanks!

**Comment by SchmockLord** [comment]
Thank you very much. You are right, I have simply forgotten to add it in my config.plist.

The others you mentioned don't have executable paths because they are Plist-only kexts. So if you open the next package you will see, that there is no subfolder macOS with an executable inside like the ones that have an executable path.

**Comment by jamesfawcett** [comment]
I've just checked my plist, I don't have the NVMeFix.kext listed either but I am using 1TB 970 EVO Plus for windows, 500gb 970 EVO Plus for Mac.

**Comment by addisonduda** [comment]
I changed my config.plist this morning to include it. I just added it as the last Item (Item 13) and checked it over 4x (lol) before rebooting. The drive temps are about 5 degrees Celsius lower and my computer actually sleeps properly now. It seems to be working well!

**Comment by jamesfawcett** [comment]
Thanks for this @addisonduda - I've added the NVMeFix.kext to mine now too. Interestingly though I still can't see the NVMe temperatures in HWMonitor, my real mac shows them so I was expecting them to.

**Comment by addisonduda** [comment]
Hmm.. that is strange. I have the temperatures listed on mine (I've attached an image). Did you add the Kexts for it? I found them here: https://hackintosher.com/guides/hwmonitor-hackintosh-guide/
<img width="282" alt="Screen Shot 2020-06-23 at 11 05 40 AM" src="https://user-images.githubusercontent.com/66935020/85425602-60d37e00-b547-11ea-9330-3f6a0620607b.png">

**Comment by SchmockLord** [comment]
My guess is: @jamesfawcett is using VirtualSMC and satellites. @addisonduda is using FakeSMC.

And I removed the NVMEFix.kext because in the german Hackintosh-forum they say it is not really required. And if the NVME-SSD is detected and Power Management is working, I think you don't really need it.

I think it was primarily to enable Compatibility and improve PM especially on High Sierra and lower.
