### ISSUE TITLE
Which dual boot strategy do you recommend?

### ISSUE THREAD

**Issue by pacifist-dev** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#85]
This is my first hackintosh build so my knowledge is limited.

I would like to dual boot windows and macos, both from internal m.2 drives. This video (https://www.youtube.com/watch?v=bnUua6hfmjs&t=1s) suggests that having both boot drives plugged in at the same time can lead to an unbootable state and maybe even risk of data loss, particularly to the MacOS drive. The solution proposed is to either only have one boot drive plugged in at a time or disable one in the bios. Neither of those are really elegant or acceptable for my use case. A third solution of using the mac bootloader is proposed, however from research it seems that there are a multitude of solutions available. 

If I'm not mistaken, from other issues it looks like @SchmockLord or maybe other users use a dual boot setup. If so, what are you using and could recommend a setup guide? Similarly, does one need to use separate BIOS profiles for each OS, and change them manually before booting between them?

This issue isn't directly relevant to this project, but since it is a common use case, perhaps it would be helpful to post a solution in the readme. Doing what others with a very similar setup have had success with seems like the path of least resistance, especially for a beginner like me.

Thanks!

**Comment by jamesfawcett** [comment]
Hello, I have dual boot windows and Mac on two separate m.2 drives. I haven't watched the YouTube video but I had no issues. I installed windows 10 first, then Catalina second and selected the other drive, no issues at all. 

When reinstalling Windows once, it did manage to overwrite my EFI folder so I could only boot Windows, but I was able to restore the EFI folder by mounting the EFI partition as Administrator in Windows, then I could boot Mac again.

**Comment by SchmockLord** [comment]
OC has improved regarding dual boot. On earlier versions I noticed, that always when I entered Windows, it felt a bit slaggy and it detected multiple unknown devices. But maybe that was because my config was not good enough and the ACPI patches e.g. were loaded. Also I always needed to login in Google Chrome/Edge again. 

Now it works and I don't have these issue anymore. But I have noticed, that e.g. in dxdiag my PC name is iMac20,2 and producer acidenthera. So there are some settings (the ones in platform info) that are still applied. 

But windows overall feels normal.

So just install Windows on a separate SSD. Windows will create its own EFI bootmanager. But it doesn't overwrite the boot priorities anymore. So you can just set OpenCore as your primary boot and then you should see an entry Windows already and can boot it from there.

**Comment by pacifist-dev** [comment]
After a few months using this setup I have not had an issue, fingers crossed. Sometimes (~5%) the computer will not boot, usually into MacOS, but a hard restart solves that and it is likely not related to this concern. Thanks for the support!
