### ISSUE TITLE
Boot with iGPU on i9 10850k

### ISSUE THREAD

**Issue by nliechti** [SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D#96]
Hey There

I am trying to install MacOS dual Boot on my Gaming rig with an Nvidia Card. As of multiple Tickets here, booting with the integrated GPU should work. I tried multiple configs for booting 10.15.7.
The Bios is configured exactly as you had it, just with the iGPU enabled for booting.

The Problem is, when I select the stick to boot from, the screen flickers 1-2s black, after that the Bios settings show up again. Sometimes with some weird graphics glitches.
Maybe anyone here has an idea what that could be, I am a bit lost with this Blackbox, as there is no other feedback.

Hardware:
* Gigabyte z490 vision d
* i9-10850K

What I already tried:

* Boot with and without dGPU installed https://github.com/18520339/Hackintosh-CometLake-Z490-OpenCore/tree/master/EFI
* With your config. https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/blob/master/EFI/OC/config_iMac20%2C2_iGPU%20with%20display%20output_with%205700XT.plist
* Config from this ticket https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/issues/40

Thanks for the help

**Comment by g3d** [comment]
@nliechti are you able to see open core when you select to boot from USB?

If no, can you please post a screenshot of your EFI drive on USB?
You should be able to see only `EFI` folder, not `BOOT` or `OC`.
![](https://files.g3d.codes/Screen-Shot-2020-11-16-18-20-23.png)

I had a similar problem, the first time I was not able to prepare the bootloader correctly (copied *from* `EFI` folder instead of copying `EFI` folder completely).

**Comment by nliechti** [comment]
Ooooooooooooooooooooooooooooooooooh man that was it. Thank you, I almost gave up on the Hackintosh project. I think I expected way harder problems 🙃.
Thanks a lot, installation is running.
